### ISSUE TITLE
Lint dcd_lpc17_40

### ISSUE THREAD

**Issue by pigrew** [hathach/tinyusb#143]
At dcd_lpc17_40.c, there is `TU_ASSERT((epnum % 3) == 3 && (epnum != 15))`.

This is always false since modulo 3 always returns between 0 and 2.

I'm not familiar with this device, so I'm not sure if it was intended to check for equality with 0?

**Comment by hathach** [comment]
thank you very much for the PR, you are dead right, I was probably coding and sleeping at the same time back then :smile:

**Comment by pigrew** [comment]
I'm playing with cppcheck; I'll push a project file for it at some point. Many of the errors are silly, but it's catching some real ones. I was really looking for a MISRA checker, but didn't find one. The TI compliers have one built-in... but yeah.

**Comment by hathach** [comment]
Yeah, I used to play with those as well. MISRA 98 is really conservative which prevent all the C99 goodies and causing lots of nowadays code user C-style comment one 1 line instead of // . The next specs MISRA 2012 is better. Too bad, I bought the specs when it debuted but still haven't finished reading (almost forgot everything now). There is also CERT C/C++  coding standard as well, those are really good one. 

Though latest gcc is really smart as well, it can check many of the cpcheck rules. Maybe I need to find way to enable those :wink:
