### ISSUE TITLE
audio_test example

### ISSUE THREAD

**Issue by petercwallis** [hathach/tinyusb#1620]
### Operating System

Linux

### Board

rp2040

### Firmware

In
 tinyusb-master/examples/device/audio_test/main.c
the body of the function audio_task() is left empty.  I have tried to modify it so that it returns a constant value at 16Mhz with 2 bytes per sample.  I believe I have modified the tusb_config.h and usb_descriptors.c correctly.

### What happened ?

rather than a nice straight line, assigning a constant for each sample (rather than a value from the microphone) produces a saw-tooth shape in Audacity.

Alsa detects a microphone via usb no problem, and I am given the option of S16_LE as a format (among others) with arecord.

### How to reproduce ?

Without listing the code, I am not sure what to say here.  my usb microphone is detected as a microphone and set up as the default under alsa. Then
open Audacity
press the record button
press the zoom in button

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by PanRe** [comment]
Hello,
this is not a bug, the `audio_test` example was written intentionally to send a sawtooth signal such that the tester can verify if all samples are received and nothing is lost due to e.g. too slow MCU or ISO driver issues or other shortcommings. The `audio_task()` is usually not used and only exists due to historical reasons - although it could be used in principle. The data sent is loaded into the audio buffers within the `tud_audio_tx_done_pre_load_cb()` callback function. This approach was chosen such that the audio buffer is loaded with samples before the next IN packet is issued by the host. Modify this function and you will see your data delivered! ;)
