### ISSUE TITLE
Effect of dcd_edpt_clear_stall

### ISSUE THREAD

**Issue by pigrew** [hathach/tinyusb#174]
I'm hunting down a bug with my USBTMC & FSDEV driver, which I believe is due to the handling of stalls.

**Should the `dcd_edpt_clear_stall` function always set the EDPT to NAK, or return it to its previous state (NAK or ACK)? Normally it will change the toggle to DATA0, if the EDPT is in NAK or ACK state, does it still reset the toggle to DATA0?**

What should happen in USBTMC is:

1. Error on endpoint (bad command, timeout, etc)
2. Class requests an EDPT stall on its bulk out EP
3. host sends CLEAR FEATURE(EP HALT)
4. device must clear the stall, and also accept new transactions on the bulk OUT EP.

So, the final question: **Does the class need to initiate a new BULK IN transfer after an EP halt, or does the core remember the previous request?** If the former, it seems the clear feature needs to be sent to the class AFTER clear_stall is called by USBD; however the class is presently getting the event before the USBD core is clearing the stall.

I see a few solutions, but I'd like input on how it is designed to work. I tried reading the various drivers, but it's hard for me to efficiently understand them.

ADDED LATER: Thinking about it a bit more, the classes should have a way to abort pending transactions, and stalling a port seems like a reasonable way to request that that port be cleared. Thus, I think the drivers should restore the port to NAK once stall is cleared. Furthermore, there needs to be a way for the class drivers to open a transaction after the endpoint has cleared the stall condition. I don't know what the "proper" fix will be, but for my personal branch, I'll modify the handling in USBD core such that if the class driver return true, the standard handler will not be called.

**Comment by hathach** [comment]
Currently  `dcd_edpt_clear_stall` will only clear stalled condition, endpoint will be go back to NAK (i.e no queued transferr. Because that stalled could be part of a set of class's procedure/protocol, and doesn't have a generic rule for USBD to handle. Let's check out this example 

1. Host send an "Unsupported Read Data Command" to OUT endpoint
2.  hw controller will just ACK that packet, and passed to usbd then class. 
3. Class will stall the IN endpoint when Host try to read the data
4. When got stalled instead of data, host knows that command is not supported ( this is up to class protocol specification). And will try to send an alternative command (maybe another revision of Read command).

>So, the final question: Does the class need to initiate a new BULK IN transfer after an EP halt, or does the core remember the previous request? If the former, it seems the clear feature needs to be sent to the class AFTER clear_stall is called by USBD; however the class is presently getting the event before the USBD core is clearing the stall.

It is best the former, so Yes, I think you are right, we should let's the usbd clear the stall first, then forward request to class later.
