### ISSUE TITLE
Disable SOF in dcd_stm32_fsdev

### ISSUE THREAD

**Issue by HiFiPhile** [hathach/tinyusb#432]
**Describe what the question is**
Since SOF is not used, could we disable it ?

**Comment by hathach** [comment]
Yes, I think it could be disabled for now since there is no use of it yet. However, please use  an macro to do that like this 
https://github.com/hathach/tinyusb/blob/master/src/portable/st/synopsys/dcd_synopsys.c#L91

So that when we need it, we can easily re-enable it without digging through commit.
