### ISSUE TITLE
hit TU_BREAKPOINT while debugging

### ISSUE THREAD

**Issue by dhalbert** [hathach/tinyusb#50]
In CircuitPython, I got this while trying to debug https://github.com/adafruit/circuitpython/issues/1686.
```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x0002d6c4 in process_control_request (p_request=0x2003f2d0, rhport=0 '\000')
    at ../../lib/tinyusb/src/device/usbd.c:407
407	    TU_BREAKPOINT();
(gdb) bt
#0  0x0002d6c4 in process_control_request (p_request=0x2003f2d0, rhport=0 '\000')
    at ../../lib/tinyusb/src/device/usbd.c:407
#1  tud_task () at ../../lib/tinyusb/src/device/usbd.c:245
#2  usb_background () at ../../supervisor/shared/usb/usb.c:78
[...]

(gdb) p *p_request
$2 = {{bmRequestType_bit = {recipient = 0 '\000', type = 0 '\000', direction = 1 '\001'}, 
    bmRequestType = 128 '\200'}, bRequest = 0 '\000', wValue = 0, wIndex = 0, wLength = 2}

```
Does the p_request look completely unreasonable, or is there request there that should be handled or ignored? I believe the computer went to sleep and then this happened; I was out of the room.

**Comment by hathach** [comment]
Thank @dhalbert it is part of suspend & resume/wakeup sequence which is not supported yet. Though I am working on it just now since I was working on this https://github.com/adafruit/circuitpython/issues/1681

Note: on nrf5x it is  able to distinguish Suspend vs Disconnect, so It could play nicely with this. So I will work on this first before porting to samd. Still didn't figure out to when suspend and disconnect in samd yet. May field test several scenario later on.
